"""
Tests for `report.py` re-created by Agent 5.

Covers pure logic in `generate_summary_report`,
`generate_transaction_detail_report`, and `format_currency_column`.
"""

import importlib
import pytest

try:
    report = importlib.import_module('report')
    _IMPORT_ERROR = None
except Exception as e:
    report = None
    _IMPORT_ERROR = e


def test_generate_summary_report_basic():
    if _IMPORT_ERROR:
        pytest.skip(f"report.py not importable: {_IMPORT_ERROR}")

    ledger = [
        {'total_revenue': 10.0, 'transaction_count': 2, 'transaction_date': '2021-01-01'},
        {'revenue_amount': '5.5', 'transactions': 1, 'transaction_date': '2021-01-02'},
    ]

    summary = report.generate_summary_report(ledger)

    assert summary['total_revenue'] == pytest.approx(15.5)
    assert summary['total_transactions'] == 3
    assert summary['entry_count'] == 2
    assert summary['period_start'] is not None
    assert summary['period_end'] is not None
    assert summary['average_transaction_value'] == pytest.approx(15.5 / 3)


def test_generate_summary_handles_empty_and_missing_fields():
    if _IMPORT_ERROR:
        pytest.skip(f"report.py not importable: {_IMPORT_ERROR}")

    summary = report.generate_summary_report([])
    assert summary['total_revenue'] == 0.0
    assert summary['total_transactions'] == 0
    assert summary['entry_count'] == 0
    assert summary['period_start'] is None
    assert summary['period_end'] is None


def test_generate_transaction_detail_report_preserves_and_enhances_rows():
    if _IMPORT_ERROR:
        pytest.skip(f"report.py not importable: {_IMPORT_ERROR}")

    ledger = [
        {'total_revenue': 5.0, 'note': 'a'},
        {'total_revenue': 7.5, 'note': 'b'},
    ]

    details = report.generate_transaction_detail_report(ledger)
    assert isinstance(details, list)
    assert len(details) == 2
    assert details[0]['sequence'] == 1
    assert details[1]['sequence'] == 2
    assert details[0]['row_id'].startswith('R')


def test_format_currency_column():
    if _IMPORT_ERROR:
        pytest.skip(f"report.py not importable: {_IMPORT_ERROR}")

    assert report.format_currency_column(1234.56) == '$1,234.56'
    assert report.format_currency_column(0) == '$0.00'
    assert report.format_currency_column('not-a-number') == 'not-a-number'
"""
Tests for `report.py` generated by Agent 5 — Test Suite Generator.

Covers `generate_summary_report`, `generate_transaction_detail_report`, and
`format_currency_column`. Tests are guarded to skip if `report.py` is
not importable (to avoid failing collection when optional deps are missing).
"""

import importlib
import pytest

try:
    report = importlib.import_module('report')
    _IMPORT_ERROR = None
except Exception as e:
    report = None
    _IMPORT_ERROR = e


def test_generate_summary_report_basic():
    if _IMPORT_ERROR:
        pytest.skip(f"report.py not importable: {_IMPORT_ERROR}")

    ledger = [
        {'total_revenue': 10.0, 'transaction_count': 2, 'transaction_date': '2021-01-01'},
        {'revenue_amount': '5.5', 'transactions': 1, 'transaction_date': '2021-01-02'},
    ]

    summary = report.generate_summary_report(ledger)

    assert summary['total_revenue'] == pytest.approx(15.5)
    assert summary['total_transactions'] == 3
    assert summary['entry_count'] == 2
    assert summary['period_start'] in ('2021-01-01', '2021-01-01')
    assert summary['period_end'] in ('2021-01-02', '2021-01-02')
    assert summary['average_transaction_value'] == pytest.approx(15.5 / 3)


def test_generate_summary_handles_empty_and_missing_fields():
    if _IMPORT_ERROR:
        pytest.skip(f"report.py not importable: {_IMPORT_ERROR}")

    summary = report.generate_summary_report([])
    assert summary['total_revenue'] == 0.0
    assert summary['total_transactions'] == 0
    assert summary['entry_count'] == 0
    assert summary['period_start'] is None
    assert summary['period_end'] is None


def test_generate_transaction_detail_report_preserves_and_enhances_rows():
    if _IMPORT_ERROR:
        pytest.skip(f"report.py not importable: {_IMPORT_ERROR}")

    ledger = [
        {'total_revenue': 5.0, 'note': 'a'},
        {'total_revenue': 7.5, 'note': 'b'},
    ]

    details = report.generate_transaction_detail_report(ledger)
    assert isinstance(details, list)
    assert len(details) == 2
    assert details[0]['sequence'] == 1
    assert details[1]['sequence'] == 2
    assert details[0]['row_id'].startswith('R')


def test_format_currency_column():
    if _IMPORT_ERROR:
        pytest.skip(f"report.py not importable: {_IMPORT_ERROR}")

    assert report.format_currency_column(1234.56) == '$1,234.56'
    assert report.format_currency_column(0) == '$0.00'
    assert report.format_currency_column('not-a-number') == 'not-a-number'


def test_export_to_excel_guarded(tmp_path):
    if _IMPORT_ERROR:
        pytest.skip(f"report.py not importable: {_IMPORT_ERROR}")

    summary = {'total_revenue': 1.0}
    details = [{'a': 1}]
    out_file = tmp_path / 'out.xlsx'

    if report.Workbook is None:
        with pytest.raises(RuntimeError):
            report.export_to_excel(summary, details, str(out_file))
    else:
        ok = report.export_to_excel(summary, details, str(out_file))
        assert ok is True
        assert out_file.exists()
