"""
Tests for `audit.py` generated by Agent 5 — Test Suite Generator.

These tests cover creation of audit entries, writing/reading the audit log,
and generating a summary report. File I/O uses `tmp_path` to avoid side effects.
"""

import importlib
import json
import pytest

try:
    audit = importlib.import_module('audit')
    _IMPORT_ERROR = None
except Exception as e:
    audit = None
    _IMPORT_ERROR = e


def test_create_audit_log_entry_fields():
    if _IMPORT_ERROR:
        pytest.skip(f"audit.py not importable: {_IMPORT_ERROR}")

    entry = audit.create_audit_log_entry('ingest_csv', {'rows': 10})
    assert 'timestamp' in entry
    assert entry['operation'] == 'ingest_csv'
    assert entry['details']['rows'] == 10
    assert entry['status'] == 'success'
    assert entry['entry_id'].startswith('audit-')


def test_write_and_read_audit_log_roundtrip(tmp_path):
    if _IMPORT_ERROR:
        pytest.skip(f"audit.py not importable: {_IMPORT_ERROR}")

    logfile = tmp_path / 'audit.log'
    entry = audit.create_audit_log_entry('op', {'input_count': 2})
    ok = audit.write_audit_log(entry, str(logfile), append=False)
    assert ok is True

    entries = audit.read_audit_log(str(logfile))
    assert isinstance(entries, list)
    assert len(entries) == 1
    assert entries[0]['operation'] == 'op'


def test_log_operation_appends_and_report(tmp_path):
    if _IMPORT_ERROR:
        pytest.skip(f"audit.py not importable: {_IMPORT_ERROR}")

    logfile = tmp_path / 'ops.log'
    # log two operations
    assert audit.log_operation('ingest', 5, 5, log_filepath=str(logfile)) is True
    assert audit.log_operation('ingest', 3, 3, log_filepath=str(logfile)) is True
    assert audit.log_operation('export', 2, 2, log_filepath=str(logfile)) is True

    report = audit.generate_audit_report(str(logfile))
    assert report['total_operations'] == 3
    assert report['operations_by_type'].get('ingest', 0) == 2
    assert report['operations_by_type'].get('export', 0) == 1
    assert report['total_records_processed'] >= 0


def test_read_audit_log_skips_malformed(tmp_path):
    if _IMPORT_ERROR:
        pytest.skip(f"audit.py not importable: {_IMPORT_ERROR}")

    logfile = tmp_path / 'bad.log'
    # write a valid line and an invalid line
    with open(logfile, 'w', encoding='utf-8') as f:
        f.write(json.dumps({'operation': 'x'}) + '\n')
        f.write('not-a-json\n')
        f.write('\n')
    entries = audit.read_audit_log(str(logfile))
    assert len(entries) == 1
